---
version: '3'
services:
  vault:
    image: vault:latest
    ports:
      - '8200:8200'
    volumes:
      - ./stores/vault/logs:/vault/logs
      - ./stores/vault/file:/vault/file
    links:
      - postgresql
  postgresql:
    image: postgres:9
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin_password
      - POSTGRES_DB=bachmanity_insanity
      - PGDATA=/var/lib/postgresql/data/bachmanity_insanity
    volumes:
      - ./stores/postgresql/data:/var/lib/postgresql/data
      - ./stores/postgresql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
  flaskapp:
    image: python:3
    environment:
      - VAULT_ROLE_ID_TOKEN
      - VAULT_SECRET_ID_TOKEN
    working_dir: /usr/src/app
    ports:
      - '80:5000'
    volumes:
      - ./python_flask_app/:/usr/src/app
    command: [ "./run_python_app.sh", "./password_manager.py" ]
    links:
      - vault
      - postgresql
